Feature/197 csstext to style
tsukuba-cojt/resta pull request #200
Opened 2024-01-14 01:49 UTC by K-Kazuyuki

ボタン追加ui周りのバグつぶしとuiの追加
次のUIが追加されている

- タイトルとcssが入力されていないときにalertの表示
- タグ追加UIの追加

2024-01-14 10:09 UTC, itsu-dev requested changes
ありがとうございます！
ぱっと見よさそうですが、作成してもボタンのタブに適用されないですね...  
あと、ボタンのタブで全ての要素に対するテンプレートが作成できてしまうのも気になります。「作成」なるタブを生やすのが妥当というところでしょうか...。

# 環境
- デバイス：Macbook Air M1, 2020
- ブラウザ：Google Chrome 120.0.6099.129（Official Build） （arm64）

# 動画
https://github.com/tsukuba-cojt/resta/assets/26784861/475cc2c7-0811-45d7-8846-b35d8235d355

2024-01-14 10:25 UTC, itsu-dev commented
@K-Kazuyuki 現状の実装のように、`CreateTemplateByCss` がタブアイテムの中にいると作成後のテンプレートリストの更新が結構面倒くさそうです。あえて一つの独立したタブアイテムとすることで、一つテンプレートを作成したあとにボタンタブに移動してもらうことで再描画が発生し、より楽にテンプレートリストの更新ができるかなと思いました。
その場合、`TemplateCustomizer#L31` の `categories` にいい感じのタブアイテムを追加してやると良さそうです。

2024-01-14 13:32 UTC, K-Kazuyuki commented
追加で、テンプレートの全削除がリロードすると復活するバグを見つけました。
修正します。

2024-01-14 14:00 UTC, K-Kazuyuki commented
バグ修正が完了しました。
現在報告されているものにはすべて対応しておりUIも別枠に追加することにしました。
若干仕様のレベルで違和感(widthなどを設定していた場合の表示をどうするか)はありますが、あまり気にするところでもないので良いかと思います。

2024-01-17 03:42 UTC, itsu-dev commented
@K-Kazuyuki ありがとうございます！一旦マージします。が、いくつか気になる点があったのでこちらで巻き取って作業しちゃいます。具体的には次の点です：
- 一度作成したテンプレートを修正することができない
- 作成したテンプレートがリストアップされない
  - 上 2 点は今回追加されたタブの中にリストアップ・修正可能にしていく方針
- テンプレートを作成したときに「作成しました」などのフィードバックがない
- 既存のテンプレート名で再度テンプレートを作成した場合、マージされている模様
  - 混乱の原因になるので、既存の名前は使用できないようにする

2024-01-17 03:43 UTC, merged